[GWL-6]
boostcampwm2023/iOS08-WeTri pull request #66
Opened 2023-11-18 15:25 UTC by JongPyoAhn

## Screenshots 📸

|iPhone15Pro|iPhoneSE|
|:-:|:-:|
|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/6b82c823-c56e-4a7a-9171-1c7d8bcac572" width="300" height="500">|<img src = "https://github.com/JongPyoAhn/Python/assets/68585628/f0b2660e-e767-446a-a5de-b2053caddc2d" width="300" height="500">|

<br/><br/>

## 고민, 과정, 근거 💬
추후 업데이트 예정입니다.

<br/><br/>

## References 📋
X

<br/><br/>

---

- Closed: #50

2023-11-18 15:45 UTC, JongPyoAhn commented
비즈니스로직 부분은 따로 Task파서 작성할 예정입니다!

2023-11-18 15:51 UTC, WhiteHyun requested changes

2023-11-18 15:51 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/RecordScene/ViewController/RecordContainerViewController.swift
> +  }
Container View Controller 활용하신 거 너무 좋습니다 👍

2023-11-18 15:51 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/RecordScene/ViewController/RecordListViewController.swift
> +  private var workoutInforamtionDataSource: WorkoutInformationDataSource?
p1: 오타났습니다!
```suggestion
  private var workoutInformationDataSource: WorkoutInformationDataSource?
```

2023-11-18 16:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/RecordScene/ViewController/RecordListViewController.swift
> +  private var workoutInforamtionDataSource: WorkoutInformationDataSource?
와우 어떻게 찾으셨나요? 🤭
저는 보고도 2번 읽어봤네요 감사합니다!

2023-11-19 01:08 UTC, WhiteHyun approved these changes
고생하셨습니다~!!

2023-11-19 16:08 UTC, MaraMincho approved these changes
고생하셨습니다!

2023-11-19 16:08 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/RecordScene/ViewController/RecordListViewController.swift
> +    button.translatesAutoresizingMaskIntoConstraints = false
P3
translatesAutoresizingMaskIntoConstraints property 위치를 통일시키면 어떨가 합니다

2023-11-20 01:03 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/RecordScene/ViewController/RecordListViewController.swift
> +    button.translatesAutoresizingMaskIntoConstraints = false
인스턴스 생성하고 바로 아래에서 설정해주는 방식으로 통일했습니다!

2023-11-20 01:03 UTC, merged