[GWL-70] Record 만들어진 UI ViewModel 구현
boostcampwm2023/iOS08-WeTri pull request #95
Opened 2023-11-21 16:45 UTC by MaraMincho

## Screenshots 📸

|Name|
|:-:|
|(image here)|

<br/><br/>

## 고민, 과정, 근거 💬

<br/><br/>

## References 📋

<br/><br/>

---

- Closed: #(issue-here)

2023-11-22 04:12 UTC, JongPyoAhn approved these changes
고생하셨습니다 다함님 :)

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Data/DTO/PeerTypeDto.swift
> +struct PeerTypeDto: Decodable {
P3

DTO를 대문자로 통일하면 좋을 것 같아요!
다른곳에는 DTO로 적어놓으셨더라구요 ㅎㅎ

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Data/DTO/GWResponse.swift
> +struct GWResponse<T>: Decodable where T: Decodable {
P3

이것도 DTO이지 않을까요?

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Data/Persistency/PeerTypes.json
> +    "description" : "혼자 진행하기",
이걸다 똑같이 시나리오 돌리셨군요..
👍

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +      let decoder = JSONDecoder()
P3

위에서 전역으로 decoder를 선언하셨습니다..!

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +    var method: Trinet.TNMethod { return .get }
P3

Trinet.은 지워도 괜찮을것 같아요~

2023-11-22 04:12 UTC, JongPyoAhn commented on iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutEnvironmentSetupUseCase.swift
> +  var cancellabels = Set<AnyCancellable>()
P3

다른곳에서는 subscriptions로 사용하셨던데, cancellables로 작명하신 이유가 있을까요?

2023-11-22 06:35 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/DTO/GWResponse.swift
> +struct GWResponse<T>: Decodable where T: Decodable {
일단 이름이 애매해서 다음과 같이 사용했습니다. 😂

2023-11-22 06:36 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/DTO/PeerTypeDto.swift
> +struct PeerTypeDto: Decodable {
확인했습니다.

2023-11-22 06:36 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +      let decoder = JSONDecoder()
ㅎㅎㅎㅎ;; ㅋㅋㅋ;; 🤣 확인했습니다.

2023-11-22 06:38 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutEnvironmentSetupUseCase.swift
> +  var cancellabels = Set<AnyCancellable>()
이부분에서 아차했습니다. 사실 Publisher로 만드는 역할은 Repository인데 불필요하게 Usecase에서 구독하는 형태여서 수정했습니다. 

현재는 받은 Publisher를 map과 Catch를 활용하여 형태만 바꾸게 해주었습니다~

2023-11-22 07:02 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/DTO/GWResponse.swift
> +struct GWResponse<T>: Decodable where T: Decodable {
아니면 DTO를 제외하고 Response, Request로 구분지어서 작명하는 것도 좋을 것 같아요.

2023-11-22 07:56 UTC, WhiteHyun requested changes
이제 구현단계에 접어들면서 제일 경계해야하는 게 PR의 크기인 것 같아요.
점점 코드량이 방대해지다보니 모든 코드를 보기가 힘들어지네요.

앞으로 구현할 때마다 잘게 PR을 나누어 연습해보는 것도 좋을 것 같습니다.
고생하셨어요!

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +  let repositorySession: URLSessionProtocol
p2: Repository가 Session을 소유하는 이유는 무엇인가요?
지금의 코드에서는 Provider에서 session을 주입해주었기에 별도로 관리할 필요성이 없어보여서요.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +  func workoutTypes() -> AnyPublisher<[WorkoutTypeDTO], Error> {
p2: 지금은 Mock Data로 테스트해서 정상적으로 받아오지만, 서버에서는 GWResponse형태로 내려받기에 조심할 필요가 있습니다.
차후에 `GWResponse<[WorkoutTypeDTO]>`로 바꿀 계획이신건지 궁금합니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +final class WorkoutEnvironmentSetupNetworkRepository: WorkoutEnvironmentSetupNetworkRepositoryRepresentable {
p3: 저는 Repository가 struct여도 상관 없을 것 같아요.
reference type의 프로퍼티를 갖고 있지도 않으니까요..!
그리고 weak self를 쓰지 않아도 된다는 장점도 갖고 있습니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +        let bundle = Bundle(identifier: PersistencyProperty.bundleIdentifier),
p3: App Target에서 실행하게 된다면 bundle이 App쪽을 따라가기 때문에 이렇게 하신건가요?
영리한 방법이네요.. 잘 써먹겠습니다 ㅎㅎ

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +
p3: 지금 보니 session을 안쓰고 Repository에서 Mock Data를 가져오는군요.
Mock Data를 가져오는 코드는 Mock Session에서 할 일이기에 별도로 구현해보는 것도 좋을 것 같습니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +  }
p3: decode라는 operator를 사용해보시면 좋을 것 같습니다!

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +}
p2: 위 의견과 같습니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Domain/Entities/PeerType.swift
> +}
p2: peerType과 WorkoutType의 id 상관관계는 없는건가요? 비슷하면서도 다른가보네요. UUID가 서로 다를 것 같아서요!

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/View/WorkoutPeerTypeSelectCell.swift
> +}
p2: info라고 했을 때 무슨 역할을 하는지 잘 모르겠어요. 어떤 함수인지 설명해주실 수 있나요?

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +}
p3: 한 줄로 줄일 수 있어보입니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +    pageControl.trailingAnchor.constraint(equalTo: safeArea.trailingAnchor, constant: -23).isActive = true
p2: 어라.. 디자인과는 다른 상수값인 것 같아요

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +    })
p2: cellProvider를 후행클로저로 빼면 더 이쁜 코드가 될 것 같아요.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/Common/Coordinator/WorkoutSettingCoordinator.swift
> +        fatalError("fillup에 Dependency를 제대로 선언하세요")
p2: fatalError.. 무섭네요. Log처리를 해주고, optional하게 리턴하는 방법은 어떨까요?

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +    })
p2: 여기도 동일한 의견입니다. 후행클로저 애용해주세요 ㅎㅎ

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +  }
p3: 아 여기서 info를 사용하는군요!
선택된 운동이 어떤 운동인지를 파악하긴 해야겠네요.
이 부분은 id값으로 대체하는 방법이 있을까요?
운동 리스트를 서버로부터 받아오게 될 텐데, 운동마다 고유 id값을 갖게 될 것 같은데요.
특정 운동 셀을 선택하게 되었다면 id값만 받아와서 서버에게 전달하면 되지 않을까 싶습니다.

2023-11-22 07:56 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewModel/WorkoutEnvironmentSetupViewModel.swift
> +      }
p1: flatMap 클로저에서 self를 강하게 참조하고 있어 retain-cycle이 일어납니다. [weak self]를 고려해보면 좋겠습니다. ☺️

2023-11-22 09:00 UTC, WhiteHyun commented
저는 컨벤션 지금 있는 그대로 가고 싶습니다. airbnb도 그렇게 하는 것 같고요 ㅎㅎ

2023-11-22 10:13 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +  let repositorySession: URLSessionProtocol
확인했습니다!

2023-11-22 10:15 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +  func workoutTypes() -> AnyPublisher<[WorkoutTypeDTO], Error> {
아마 예전, MockData를 넣어서 Network에서 받아 올 때는 GWRresponse 포멧의 Json이었는데 현재는 내부 데이터라 [Type]에 대해서 기재했네요. 내부 Json 파일도 GWRresponse로 갖고 있어도 나쁘지 않을 것 같다는 생각입니다.

2023-11-22 11:10 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +final class WorkoutEnvironmentSetupNetworkRepository: WorkoutEnvironmentSetupNetworkRepositoryRepresentable {
좋은것 같습니다!

2023-11-22 11:15 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +
두가지 경우를 생각했습니다.
1. 서버에서 peer를 가져온다 2. localJson에서 가져온다.

두가지를 커버하기 위해서, 한 파일에 넣었습니다. 현재는 API가 없어서, 일단 내부 파일로 구현했고 차후 API가 완성되면 통신 이후 Json을 내부 파일로 넣어서 처리할 예정이었습니다.

"MockSession에서 할 일" 이란 무엇일까에 대해서 고민해봤는데 질문의 의도를 모르겠습니다. 혹시 보충 설명 해주실 수 있을까요?

2023-11-22 11:22 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Domain/Entities/PeerType.swift
> +}
이거 원래 DiffableDataSource할 때 데이터가 위변조로 인해서, 중복 데이터가 오게 된다면 DiffableDataSource가 고장나게 됩니다. 이를 안전장치로 달아 두었습니다. 하지만 생각해 보니, 사용자 입장에서 uuid만 다른 obejct가 cell로 보여지게 된다면 그것 또한 버그라고 생각됩니다. 따라서 UUID를 지우고 unique한 객체가 될 수 있도록 코드를 수정했습니다.

2023-11-22 11:26 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +    pageControl.trailingAnchor.constraint(equalTo: safeArea.trailingAnchor, constant: -23).isActive = true
헉...! 감사합니다

2023-11-22 11:30 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewController/WorkoutEnvironmentSetupViewController.swift
> +    })
확인했습니다~

2023-11-22 12:06 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Presentation/WorkoutEnvironmentScene/ViewModel/WorkoutEnvironmentSetupViewModel.swift
> +      }
확인했습니다!

2023-11-22 12:30 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Domain/UseCases/WorkoutEnvironmentSetupUseCase.swift
> +}
이거 Interfaces/Repositories가 맞을까요 Dombain/RepositoryInterfaces/가 맞을까요?
둘다 좋지만, Interfaces의 개념 보다는 어느 역할을 하는지가 중요하다면 둘의 폴더를 Domain 아래에 두는 것도 좋아보입니다. 승현님 생각이 궁금합니다.

2023-11-22 13:12 UTC, WhiteHyun commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +
레포지토리에서는 Session을 이용해서 데이터를 요청하고, 데이터가 어떻게 들어올 것인지는 Session에서 해야하는 역할이라고 생각했습니다.
지금 코드에서는 Session을 주입받되, 사용하지 않는 것 같아보였어요.
즉, 외부에서 MockSession을 주입하고, MockSession에는 Mock JSON의 데이터를 넘겨주는 방법으로 처리하는 게 어떨까 싶어 제시한 의견이었습니다. ㅎㅎ

2023-11-23 05:03 UTC, MaraMincho commented on iOS/Projects/Features/Record/Sources/Data/Repositories/WorkoutEnvironmentSetupNetworkRepository.swift
> +}
이거 decode를 사용하지 않은 이유는, 데이터가 혹시 잘못되었을 수도 있다고 생각했습니다.

struct GWResponse<T>: Decodable where T: Decodable {
  let code: Int?
  let errorMessage: String?
  let data: T?
}

인데, data의 T가 optional이면 따로 또 분기처리해야하지 않나요? 혹시 방법이 있는지 궁금합니다...!

2023-11-23 05:27 UTC, WhiteHyun approved these changes
LGTM ❤️

2023-11-23 07:57 UTC, merged